# Generated by Django 4.0.6 on 2022-08-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProCod', models.CharField(max_length=100)),
                ('ProNom', models.CharField(max_length=100)),
                ('ProCantSto', models.CharField(max_length=100)),
                ('ProNumCodBar', models.CharField(max_length=100)),
                ('ProLinIma', models.CharField(max_length=100)),
                ('ProPreUni', models.CharField(max_length=100)),
            ],
        ),
    ]
