# Generated by Django 4.0.6 on 2022-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProCantSto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProNumCodBar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProPreUni',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
