# Generated by Django 4.0.6 on 2022-08-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GasCod', models.CharField(max_length=100)),
                ('GasNom', models.CharField(max_length=100)),
                ('GasForPagCod', models.CharField(max_length=100)),
                ('GasDes', models.CharField(max_length=100)),
                ('GasFec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemCod', models.CharField(max_length=100)),
                ('MemNom', models.CharField(max_length=100)),
                ('MemDes', models.CharField(max_length=100)),
                ('MemCanMes', models.CharField(max_length=100)),
                ('MemPre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenCod', models.CharField(max_length=100)),
                ('VenProCod', models.CharField(max_length=100)),
                ('VenCliCod', models.CharField(max_length=100)),
                ('VenForPagCod', models.CharField(max_length=100)),
                ('VenFec', models.CharField(max_length=100)),
            ],
        ),
    ]
