# Generated by Django 4.0.6 on 2022-08-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='MemCanMes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='MemPre',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='venta',
            name='VenFec',
            field=models.DateField(),
        ),
    ]
