# Generated by Django 4.0.6 on 2022-08-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EveCod', models.CharField(max_length=100)),
                ('EveNom', models.CharField(max_length=100)),
                ('EveFecDiaHorIni', models.CharField(max_length=100)),
                ('EveFecDiaHorFin', models.CharField(max_length=100)),
                ('EveInsCod', models.CharField(max_length=100)),
                ('EvePre', models.CharField(max_length=100)),
            ],
        ),
    ]
