# Generated by Django 4.0.6 on 2022-08-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CliEveCod', models.CharField(max_length=100)),
                ('CliEveCliCod', models.CharField(max_length=100)),
                ('CliEveInsCod', models.CharField(max_length=100)),
                ('CliEveFecDiaHorIni', models.CharField(max_length=100)),
                ('CliEveFecDiaHorFin', models.CharField(max_length=100)),
                ('CliEveEst', models.CharField(max_length=100)),
            ],
        ),
    ]
