# Generated by Django 4.0.6 on 2022-08-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_cliente_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_evento',
            name='CliEveEst',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente_evento',
            name='CliEveFecDiaHorFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente_evento',
            name='CliEveFecDiaHorIni',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='EveFecDiaHorFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='EveFecDiaHorIni',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='EvePre',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
