# Generated by Django 4.0.6 on 2022-08-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CliCode', models.CharField(max_length=100)),
                ('CliNom', models.CharField(max_length=100)),
                ('CliEma', models.CharField(max_length=100)),
                ('CliPas', models.CharField(max_length=100)),
                ('CliNumTel', models.CharField(max_length=100)),
                ('CliTipDoc', models.CharField(max_length=100)),
                ('CliNumDoc', models.CharField(max_length=100)),
                ('CliFecCum', models.CharField(max_length=100)),
                ('CliHueDig', models.CharField(max_length=100)),
                ('CliMemCod', models.CharField(max_length=100)),
                ('CliMemIni', models.CharField(max_length=100)),
                ('CliMemFin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InsCod', models.CharField(max_length=100)),
                ('InsNom', models.CharField(max_length=100)),
                ('InsEma', models.CharField(max_length=100)),
                ('InsPas', models.CharField(max_length=100)),
                ('InsTipDoc', models.CharField(max_length=100)),
                ('InsNumDoc', models.CharField(max_length=100)),
                ('InsNumTel', models.CharField(max_length=100)),
                ('InsFecCum', models.CharField(max_length=100)),
                ('InsHueDig', models.CharField(max_length=100)),
                ('InsFecIni', models.CharField(max_length=100)),
            ],
        ),
    ]
