# Generated by Django 4.0.6 on 2022-08-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CliCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliEma',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliFecCum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliHueDig',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliMemCod',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliMemFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliMemIni',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliNumDoc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliNumTel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CliTipDoc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsCod',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsEma',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsFecCum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsFecIni',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsHueDig',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsNumDoc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsNumTel',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='InsTipDoc',
            field=models.IntegerField(),
        ),
    ]
