# Generated by Django 4.0.6 on 2022-08-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_instructor_insnumtel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CliTipDoc',
            field=models.CharField(max_length=100),
        ),
    ]
