# Generated by Django 4.0.6 on 2022-08-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RutCod', models.CharField(max_length=100)),
                ('RutNom', models.CharField(max_length=100)),
                ('RutCarPes', models.CharField(max_length=100)),
                ('RutNumRep', models.CharField(max_length=100)),
                ('RutInsCod', models.CharField(max_length=100)),
                ('RutDes', models.CharField(max_length=100)),
            ],
        ),
    ]
