# Generated by Django 4.0.6 on 2022-08-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rutinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CliRutCliCod', models.CharField(max_length=100)),
                ('CliRutInsCod', models.CharField(max_length=100)),
                ('CliRutFecDia', models.CharField(max_length=100)),
                ('CliRutEst', models.CharField(max_length=100)),
            ],
        ),
    ]
