# Generated by Django 4.0.6 on 2022-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rutinas', '0002_cliente_rutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_rutina',
            name='CliRutEst',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente_rutina',
            name='CliRutFecDia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='RutCarPes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='RutNumRep',
            field=models.IntegerField(),
        ),
    ]
